# Generated by Django 3.2.5 on 2021-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_agenda',
            field=models.DateField(auto_now_add=True),
        ),
    ]
