# Generated by Django 3.2.5 on 2021-09-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agenda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='user',
        ),
    ]
