# Generated by Django 3.2.5 on 2021-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20210902_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_agenda',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
