# Generated by Django 3.2.5 on 2021-07-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
