# Generated by Django 3.2.9 on 2021-11-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(choices=[('1', 'Consultas'), ('2', 'Sugerencias'), ('3', 'Otros')], max_length=100, verbose_name='Asunto'),
        ),
    ]
