# Generated by Django 3.2.9 on 2021-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contacto_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Consultas'), (2, 'Sugerencias'), (3, 'Otros')]),
        ),
    ]
